begin: сделать работоспособную версию
a-mihalych/java-filmorate pull request #1
Opened 2022-11-04 23:53 UTC by a-mihalych

2022-11-06 12:28 UTC, ohelly requested changes
Привет! В целом отличная работа, все работает правильно. Необходимо исправить несколько технических моментов связанных со структурой кода.

2022-11-06 12:28 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +public class Film {
Необходимо исправить: В классах моделях поля не должны быть final, так как из за этого их создание возможно только через билдер и это также не дает менять значения этим полям с помощью сеттера.

Аналогичная проблема с моделью User

2022-11-06 12:28 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public final static LocalDate BEGIN_OF_CINEMA_ERA = LocalDate.of(1895, 12, 28);
Рекомендация: Для данной проверки на дату для фильма также можно написать свою аннотацию. https://blog.clairvoyantsoft.com/spring-boot-creating-a-custom-annotation-for-validation-edafbf9a97a4

2022-11-06 12:28 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private Map<Integer, Film> films = new HashMap<>();
Необходимо исправить: Необходимо создать сервисный класс, в котором и будет происходить дополнительная валидация, а также сохранение, получение и обновление фильмов. Необходимо придерживаться следующего флоу Контроллер -> Сервис -> Репозиторий. Слой Репозитория можно на данном этапе отпустить и сделать его прямо в сервисе. Обычно контроллер только принимает данные на вход и направляет их в сервисный класс, где и происходит вся остальная логика.

Аналогичная проблема и в классе UserController.

2022-11-06 12:28 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getLogin().contains(" ")) {
Рекомендация: Для проверки на пробелы в логине можно также написать дополнительную собственную аннотацию или воспользоваться готовой аннотацией @Pattern(regexp = ""), где regexp - регулярное выражение

2022-11-06 12:28 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            error += (method + "пользователя прервано! Дата рождения не может быть в будущем.\n");
Рекомендация: Проверка на дату рождения здесь лишняя, так как в модели у данного поля уже есть аннотация для проверки этого(@PastOrPresent), которая срабатывает если попробовать сделать запрос с неверными данными, например через постман.

2022-11-08 11:38 UTC, a-mihalych commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +public class Film {
Сделал, поля теперь не final.

2022-11-08 11:39 UTC, a-mihalych commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public final static LocalDate BEGIN_OF_CINEMA_ERA = LocalDate.of(1895, 12, 28);
Сделано. Написал свою аннотацию.

2022-11-08 11:41 UTC, a-mihalych commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getLogin().contains(" ")) {
Сделано. Применил аннотацию @pattern с регулярным выражением.

2022-11-08 11:41 UTC, a-mihalych commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            error += (method + "пользователя прервано! Дата рождения не может быть в будущем.\n");
Исправил. Лишнюю проверку убрал.

2022-11-08 11:44 UTC, a-mihalych commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private Map<Integer, Film> films = new HashMap<>();
Не сделано. Обсудили в слак, оставлено как рекомендация, тема следующего спринта.

2022-11-08 16:28 UTC, ohelly approved these changes
Отличная работа! Все замечания исправлены.

2022-11-08 16:28 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int id;
Рекомендация: Для идентификаторов лучше использовать классы обертки(Long или Integer), так как примитивные типы не могут иметь значение null(0 по дефолту). Из-за это при создании нового объекта его идентификатор равен 0 вместо null, что может привести к коллизиям.

2022-11-08 16:28 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/validation/BeginOfCinemaEraValidator.java
> +        return !date.isBefore(BEGIN_OF_CINEMA_ERA);
Рекомендация: Сейчас если попробовать отправить запрос на создание фильма и не задать поле releaseDate выкидывается ``NullPointerException`` так как в данном методе отсутствует проверка на date != null, хоть над полем и стоит аннотация ``@NotNull``. Это происходит из за того, что порядок выполнения аннотаций разный.

P.S. Отметил как рекомендацию, но к следующему спринту необходимо исправить.

2022-11-16 16:46 UTC, merged