feat: добавить друзей и рейтинг фильмов
a-mihalych/java-filmorate pull request #2
Opened 2022-11-20 21:14 UTC by a-mihalych

2022-11-21 21:06 UTC, ohelly requested changes
Привет! В целом отличная работа, прекрасная разбивка кода по классам  валидация ошибок. Есть несколько замечаний, которые необходимо исправить, также я оставил несколько рекомендаций, на которые стоит обратить внимание.

2022-11-21 21:06 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +package ru.yandex.practicum.filmorate.controller;
Рекомендация: Для данного класса можно создать отдельный подпакет, например handler, так как он уже не контроллер, но относится к их логике.

2022-11-21 21:06 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/exception/FilmorateException.java
> +public class FilmorateException extends Exception {
Рекомендация: Ексепшены можно наследовать от RuntimeException, вместо Exception. Благодаря этому нам не придется кучу throws в сигнатурах методов.

Аналогично и с другими ексепшенами.

2022-11-21 21:06 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private FilmService filmService;
Рекомендация: Поле filmService можно сделать final, так как оно не изменяется и инициализируется в конструкторе. Также благодаря этому, можно "избавиться" от конструктора. У ломбока есть аннотация `@RequiredArgsConstructor`, которая добавляет конструктор, включающий в себя параметры всех финальных полей.

Также это применимо ко всем другим контроллерам/сервисам/компонентам, где используется инъекция зависимостей.

2022-11-21 21:06 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/exception/validation/BeginOfCinemaEra.java
> +package ru.yandex.practicum.filmorate.exception.validation;
Рекомендация: Пакет validation лучше вынести из пакета exception, так как они к ним не относятся, они лишь инициализируют проверку необходимых полей.

2022-11-21 21:06 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    ValidationService validationService;
Необходимо исправить: Поля данного класса должны быть private, так как они используются только внутри этого класса.

2022-11-21 21:06 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    ValidationService validationService;
Необходимо исправить: Поля данного класса должны быть private, так как они больше нигде не используются.

2022-11-21 21:06 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public UserService(InMemoryUserStorage userStorage, ValidationService validationService) {
Необходимо исправить: Параметр userStorage должен быть интерфейс, а не его реализация: public UserService(UserStorage userStorage ...)

2022-11-21 21:06 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(InMemoryFilmStorage filmStorage, ValidationService validationService) {
Необходимо исправить: Параметр filmStorage должен быть интерфейс, а не его реализация: public FilmService(FilmStorage filmStorage ...)

2022-11-21 21:06 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/ValidationService.java
> +public class ValidationService {
Здорово, что сделан отдельный класс для валидации объектов.

2022-11-21 21:06 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/ValidationService.java
> +    UserStorage userStorage;
Необходимо исправить: Поля данного класса должны быть private, так как они больше нигде не используются.

2022-11-21 21:06 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/ValidationService.java
> +            if ((userCollection.getId() != user.getId()) && (userCollection.getLogin().equals(user.getLogin()))) {
Необходимо исправить: ...getId() != user.getId(). Через оператор `!=` можно сравнивать только примитивные типы, а идентификатор у нас Integer, что уже является объектом, таким образом объекты  сравнить не получится, необходимо использовать метод equals.

`!=` не сработает, потому что сами объекты это по сути ссылки на участки памяти, поэтому у двух идентификаторов типа Integer может быть одинаковое значение, но разные объекты и тогда оператор != вернет true.

2022-11-21 21:06 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/ValidationService.java
> +            throw new NotFoundException(error);
Рекомендация: Для данного случая лучше подойдет ValidationException, вместо NotFoundException, так как проблема возникла при валидации, а не при поиске.

2022-11-21 21:06 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    private Map<Integer, Set<Integer>> likes = new HashMap<>();
Рекомендация: Необходимо likes перенести в модель Film(добавить поле Set<Integer> в класс Film, так как они относятся к ним, то есть входят в состав фильма. Поработать сейчас над этим отличная возможность потренироваться, так как дальше при работе с БД будет много похожих случаев и различные связи сущностей(один ко одному, многие к одному и тд)

2022-11-21 21:06 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    private Map<Integer, Set<Integer>> friends = new HashMap<>();
Рекомендация: Необходимо friends перенести в модель User(добавить поле Set<Integer> в класс User, так как они относятся к юзерам, то есть входят в состав юзер. Поработать сейчас над этим отличная возможность потренироваться, так как дальше при работе с БД будет много похожих случаев и различные связи сущностей(один ко одному, многие к одному и тд)

2022-11-22 13:09 UTC, a-mihalych commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +package ru.yandex.practicum.filmorate.controller;
Сделано.

2022-11-22 13:10 UTC, a-mihalych commented on src/main/java/ru/yandex/practicum/filmorate/exception/FilmorateException.java
> +public class FilmorateException extends Exception {
Сделано.

2022-11-22 13:10 UTC, a-mihalych commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private FilmService filmService;
Сделано.

2022-11-22 13:10 UTC, a-mihalych commented on src/main/java/ru/yandex/practicum/filmorate/exception/validation/BeginOfCinemaEra.java
> +package ru.yandex.practicum.filmorate.exception.validation;
Сделано.

2022-11-22 13:11 UTC, a-mihalych commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    ValidationService validationService;
Сделано.

2022-11-22 13:11 UTC, a-mihalych commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    ValidationService validationService;
Сделано.

2022-11-22 13:12 UTC, a-mihalych commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public UserService(InMemoryUserStorage userStorage, ValidationService validationService) {
Этот конструктор убрал.

2022-11-22 13:12 UTC, a-mihalych commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(InMemoryFilmStorage filmStorage, ValidationService validationService) {
Этот конструктор убрал.

2022-11-22 13:13 UTC, a-mihalych commented on src/main/java/ru/yandex/practicum/filmorate/service/ValidationService.java
> +public class ValidationService {
Спасибо!

2022-11-22 13:13 UTC, a-mihalych commented on src/main/java/ru/yandex/practicum/filmorate/service/ValidationService.java
> +    UserStorage userStorage;
Сделано.

2022-11-22 13:13 UTC, a-mihalych commented on src/main/java/ru/yandex/practicum/filmorate/service/ValidationService.java
> +            if ((userCollection.getId() != user.getId()) && (userCollection.getLogin().equals(user.getLogin()))) {
Сделано.

2022-11-22 13:14 UTC, a-mihalych commented on src/main/java/ru/yandex/practicum/filmorate/service/ValidationService.java
> +            throw new NotFoundException(error);
Не сделано. Да, у меня изначально тут так и было (ValidationException), но тесты, которые написаны разработчиками курса, проверяющие наши работы в Postman не пропускают эту ошибку.

2022-11-22 13:15 UTC, a-mihalych commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    private Map<Integer, Set<Integer>> likes = new HashMap<>();
Не сделано. На вебинаре, наставник нам показывал эту реализацию с размещением likes в модели и сказал, что это допустимо в этой работе, но не очень хорошо. Лучше если это будет храниться в storage, но это сложнее реализовать, но более правильно. Я решил сделать этот, по его словам, более правильный и сложный вариант. Если вы оставите эту рекомендацию, я сделаю, хоть и отстаю на пару дней от графика, но хотелось бы оставить этот вариант, если он и в самом деле более правильный, или, просто только потренироваться, но в итоге оставить этот вариант.

2022-11-22 13:15 UTC, a-mihalych commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    private Map<Integer, Set<Integer>> friends = new HashMap<>();
Не сделано. Не стал копировать ответ с предыдущей рекомендации, тут аналогично.

2022-11-22 17:27 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/ValidationService.java
> +            throw new NotFoundException(error);
Хм, это наверное потому что нигде нет требования, что идентификатор должен положительным, поэтому они отправляют значение, которого нет в хранилище и ждут not found.

2022-11-22 17:30 UTC, ohelly approved these changes
Отличная работа! Теперь все работает корректно. Работу принимаю, удачи в дальнейшем обучении!

2022-12-05 09:17 UTC, merged