feat: добавить базу данных
a-mihalych/java-filmorate pull request #3
Opened 2022-12-16 14:31 UTC by a-mihalych

2022-12-17 14:25 UTC, ohelly requested changes
Привет! В целом отличная работа, все работает правильно, но есть несколько замечаний, которые необходимо исправить. В основном они связаны с тем, что логика для разных таблиц(сущностей) не разделена по классам, а также есть проблема в том, что когда мы достаем из БД несколько фильмов, то мы делаем по запросу для каждого фильма в БД для получения жанров, а должен выполняться только один запрос.

В случае возникновения вопросов можно обратиться ко мне в пачку.

2022-12-17 14:25 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +public class FilmDbStorage implements FilmStorage {
Необходимо исправить: В данном классе есть методы связанные с лайками(добавление, удаление и т.д.). Эти методы должны быть вынесены в отдельный storage, например LikeDbStorage.

Аналогично с методами по добавлению и удалению друзей в UserDbStorage, которые тоже должны быть вынесены в отдельный класс FriendDbStorage.

Хорошая практика, когда один Storage отвечают только за одну таблицу(сущность) в БД.

Также из данного класса можно вынести методы связанные с жанрами в GenreDbStorage.

2022-12-17 14:25 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +public class FilmDbStorage implements FilmStorage {
Необходимо исправить: В данном классе есть методы связанные с лайками(добавление, удаление и т.д.). Эти методы должны быть вынесены в отдельный storage, например LikeDbStorage.

Аналогично с методами по добавлению и удалению друзей в UserDbStorage, которые тоже должны быть вынесены в отдельный класс FriendDbStorage.

Хорошая практика, когда один Storage отвечают только за одну таблицу(сущность) в БД.

Также из данного класса можно вынести методы связанные с жанрами в GenreDbStorage.

2022-12-17 14:25 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    private Film makeFilm(ResultSet resultSet) throws SQLException {
Необходимо исправить: В данном методе не должно быть логики связанной с получением жанров фильмов. Это должен быть отдельный метод, который будут вызываться отдельно. То есть в классе FilmService, в методе получения одного или всех нескольких фильмов, мы должны вызывать метод получения фильма/фильмов: ``filmStorage.getFilm(id);``, а затем следующей строкой вызывать метод по получению жанров: ``filmStorage.getGenre(filmId);``, а затем засетить жанры в фильм: ``film.setGenres(genres)``.

Также метод по получению жанров должен делать один запрос в БД, независимо от того, ищем мы жанры для нескольких фильмов или одного. Чтобы этого достичь можно использовать HashMap и запрос с оператором IN

2022-12-17 14:25 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        SqlRowSet sqlRowSet = jdbcTemplate.queryForRowSet(sql, id);
Здорово, что используется SqlRowSet!

2022-12-17 14:25 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +            return User.builder()
Рекомендация: Предлагаю вынести часть кода, которая билдит юзера в отдельный метод, по аналогии с makeUser. Также можно отказаться от SqlRowSet и доставать одного пользователя следующим образом: 
```
List<User> users = jdbcTemplate.query(sql, this::makeUser, id);
if (users.size() != 1) {
//выводим ошибку
} else {
return user.get(0);
}
```

Также применимо и в классе FimDbStorage

2022-12-17 14:25 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +                stmt.setNull(4, Types.DATE);
Необходимо исправить: Так как birthday может быть null, то необходимо в методе makeUser проверять, что BIRTHDAY поле != null, иначе будет выскакивать NullPoinerException

Аналогичное замечание к полю RELEASEDATE в FilmDbStorage

2022-12-18 16:27 UTC, a-mihalych commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +public class FilmDbStorage implements FilmStorage {
Сделано. Добавлены LikeDbStorage и FriendDbStorage, а в GenreDbStorage вынесены некоторые методы.

2022-12-18 16:29 UTC, a-mihalych commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +public class FilmDbStorage implements FilmStorage {
Сделано. Добавлены LikeDbStorage и FriendDbStorage, а в GenreDbStorage вынесены некоторые методы.

2022-12-18 16:32 UTC, a-mihalych commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    private Film makeFilm(ResultSet resultSet) throws SQLException {
Сделано. Вынес отсюда логику получения жанров. Делается один запрос на получение фильмов и один запрос на получение жанров, в не зависимости от количества фильмов.

2022-12-18 16:33 UTC, a-mihalych commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +            return User.builder()
Сделано. Делается запрос как предложено.

2022-12-18 16:35 UTC, a-mihalych commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +                stmt.setNull(4, Types.DATE);
Даты ограничены аннотацией в моделях и в базе not null.

2022-12-18 21:26 UTC, ohelly approved these changes
Отличная работа, исправлены все замечания. Работа принята, удачи в дальнейшем обучении!

2022-12-19 21:17 UTC, merged